services:
  db:
    image: postgis/postgis:15-3.3
    container_name: civickit-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: civickit
    ports:
      - "5432:5432"
    volumes:
      - civickit-data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    container_name: civickit-jaegertrace
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "4318:4318"

volumes:
  civickit-data:
